SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;
BEGIN
SELECT count(*) into nCount FROM user_tables where table_name = 'REGIONCODES';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('REGIONCODES TABLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE REGIONCODES(
REGCD varchar(10) PRIMARY KEY,
DES varchar(20) NOT NULL,
TIMEZONE varchar(10),
CONSTRAINT check_tmzone CHECK 
(TIMEZONE IN (''EST'',''IST'',''PST'',''GMT'',''CST'',''SST'')))';


END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'ADDRESS';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('ADDRESS TABLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE ADDRESS(
    COUNTRYCD varchar(10) PRIMARY KEY,
    COUNTRYNAME varchar(20) NOT NULL,
    REGIONCODE varchar(10) REFERENCES REGIONCODES(REGCD))';

END IF;


END;