SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;
BEGIN
SELECT count(*) into nCount FROM user_tables where table_name = 'REGIONCODES';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('REGIONCODES TABLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE REGIONCODES(
REGCD varchar(10) PRIMARY KEY,
DES varchar(20) NOT NULL,
TIMEZONE varchar(10),
CONSTRAINT check_tmzone CHECK 
(TIMEZONE IN (''EST'',''IST'',''PST'',''GMT'',''CST'',''SST'')))';

EXECUTE IMMEDIATE 'INSERT INTO REGIONCODES VALUES(''R001'',''NorthAmerica_Est'',''EST'')';
EXECUTE IMMEDIATE 'INSERT INTO REGIONCODES VALUES(''R002'',''NorthAmerica_Pst'',''PST'')';
EXECUTE IMMEDIATE 'INSERT INTO REGIONCODES VALUES(''R003'',''Singapore_Sst'',''SST'')';



END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'ADDRESS';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('ADDRESS TABLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE ADDRESS(
    ADDRCODE varchar(10) PRIMARY KEY,
    COUNTRYNAME varchar(50) NOT NULL,
    PROVINCE varchar2(50) NOT NULL,
    REGIONCODE varchar(10) REFERENCES REGIONCODES(REGCD))';
    
    EXECUTE IMMEDIATE 'INSERT INTO ADDRESS VALUES(''A01'',''United States of America'',''Massachusetts'',''R001'')';
    EXECUTE IMMEDIATE 'INSERT INTO ADDRESS VALUES(''A02'',''United States of America'',''New Hampshire'',''R001'')';
    EXECUTE IMMEDIATE 'INSERT INTO ADDRESS VALUES(''A03'',''United States of America'',''California'',''R002'')';
    EXECUTE IMMEDIATE 'INSERT INTO ADDRESS VALUES(''A04'',''United States of America'',''Oregon'',''R002'')';
    EXECUTE IMMEDIATE 'INSERT INTO ADDRESS VALUES(''A05'',''Singapore'',''North East Community'',''R003'')';
    EXECUTE IMMEDIATE 'INSERT INTO ADDRESS VALUES(''A06'',''Malaysia'',''Johor'',''R003'')';


END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'CUSTOMER';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('CUSTOMER TABLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE CUSTOMER(
    CUSTOMERID VARCHAR(10) PRIMARY KEY,
    CUSTNAME VARCHAR(20) NOT NULL,
    CONTACT NUMBER(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ACCOUNT VARCHAR(20) NOT NULL,
    ADDR VARCHAR(10) REFERENCES ADDRESS(ADDRCODE),
    BUYINGPOWER NUMBER(10) NOT NULL,
    USERNAME VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    CHECK (EMAIL LIKE ''%@%com%''))';

END IF;
END;