  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."MY_SHARES" ("CUST_NAME", "SEC_DESC", "QTY", "AS_OF_DATE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT C.CUST_NAME, CS.SEC_DESC, CH.QTY, CH.ASOFDATE "AS_OF_DATE"
FROM CUSTOMER C JOIN CUSTOMERHOLDING CH
ON 
C.CUST_ID=CH.CUSTOMERID
JOIN 
COMPANYSECURITY CS
ON CH.SECURITYID = CS.SECURITY_ID
where UPPER(C.CUST_USERNAME) =(SELECT user FROM DUAL);


  GRANT SELECT ON "ADMIN"."MY_SHARES" TO "DB_CUSTOMERS"