SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;
BEGIN

SELECT count(*) into nCount 
FROM user_tables 
WHERE table_name='STOCKINFO';
IF(nCount>0)
THEN
    DBMS_OUTPUT.PUT_LINE('STOCKINFO TABLE ALREADY EXISTS');    
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE STOCKINFO(
    STOCKID varchar(10) PRIMARY KEY,
    ASOFDATE DATE UNIQUE,
    MARKETVAL NUMBER(10),
    QTYAVAILABLE NUMBER(10),
    CONSTRAINT check_date CHECK (extract(day from ASOFDATE) = 1))';

SELECT count(*) into nCount 
FROM user_tables 
WHERE table_name='STOCKEXCHANGE';
IF(nCount>0)
THEN
    DBMS_OUTPUT.PUT_LINE('STOCKEXCHANGE TABLE ALREADY EXISTS');    
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE STOCKEXCHANGE(
    EXCHID NUMBER(10) PRIMARY KEY,
    EXCHNAME VARCHAR(30) NOT NULL,
    COMPID NUMBER(10) NOT NULL,
    FOREIGN KEY(COMPID) REFERENCES COMPANY(COMPANYID))';


END IF;
END;