---VIEW ALL SHARES---
CREATE OR REPLACE VIEW ALL_SHARES AS
SELECT CS.SEC_DESC AS SECURITY_NAME, SI.MARKET_VAL FROM 
(select stock_id,market_val from
(SELECT stock_id,market_val, rank() over (partition by stock_id order by as_of_date desc) as rank from stockinfo)
stock_curr 
where stock_curr.rank=1) SI
join COMPANYSECURITY CS
on  CS.SECURITY_ID = SI.STOCK_ID;

SELECT * FROM ALL_SHARES;

---VIEW MY SHARES---




CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."MY_SHARES" ("CUST_NAME", "SEC_DESC", "QTY", "AS_OF_DATE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
SELECT C.CUST_NAME, CS.SEC_DESC, CH.QTY, CH.ASOFDATE "AS_OF_DATE"
FROM CUSTOMER C JOIN CUSTOMERHOLDING CH
ON 
C.CUST_ID=CH.CUSTOMERID
JOIN 
COMPANYSECURITY CS
ON CH.SECURITYID = CS.SECURITY_ID
where UPPER(C.CUST_USERNAME) =(SELECT user FROM DUAL);


GRANT SELECT ON "ADMIN"."MY_SHARES" TO "DB_CUSTOMERS";

SELECT * FROM MY_SHARES;